version: '3'
services:
  core:
    image: "${DHIS2_APPHUB_IMAGE}"
    restart: unless-stopped
    ports:
      - "${DHIS2_APPHUB_PORT}:3000"
    env_file: .apphub.env
    depends_on:
      - db
    links:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.covid19-https.redirectscheme.scheme=https"
      - "traefik.http.routers.covid19-http.entrypoints=web"
      - "traefik.http.routers.covid19-http.rule=Host(`covid19.example.com`)" #Domain anpassen
      - "traefik.http.routers.covid19-http.middlewares=covid19-https@docker"
      - "traefik.http.routers.covid19.entrypoints=web-secure"
      - "traefik.http.routers.covid19.rule=Host(`covid19.example.com`)" #Domain anpassen
      - "traefik.http.routers.covid19.tls=true"
      - "traefik.http.routers.covid19.tls.certresolver=default"
      - "traefik.http.routers.covid19.middlewares=secHeaders@file"
      - "traefik.http.services.covid19.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
      
  db:
    image: dhis2/postgres-contrib
    restart: unless-stopped
    environment:
       POSTGRES_DB: app-hub
       POSTGRES_USER: app-hub
       POSTGRES_PASSWORD: app-hub

